version: '3.7'
services:
  daphne:
    build:
      dockerfile: ./build/Dockerfile
      context: .
    image: daphne:test
    volumes:
      - type: bind
        source: ${ROOT_DIR}/codebase
        target: /app/daphne
      - type: bind
        source: ${ROOT_DIR}/build/scripts
        target: /app/scripts
      - type: bind
        source: ${ROOT_DIR}/logs
        target: /app/logs
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - postgres
    tty: true
    container_name: daphne_server
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=daphne
      - POSTGRES_PASSWORD=daphne
      - POSTGRES_DB=daphne
    container_name: daphne_database
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: daphne_redis
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    hostname: "my-rabbitmq"
    container_name: daphne_rabbitmq
  neo4j:
    image: neo4j:3.5.14
    ports: 
      - "7474:7474"
      - "7687:7687"
    container_name: neo4j_daphne
    volumes: 
      - ${ROOT_DIR}/databases/neo4j/data:/data
      - ${ROOT_DIR}/databases/neo4j/logs:/logs
    environment: 
      - NEO4J_AUTH=neo4j/test
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    container_name: pgadmin_daphne
    environment: 
      - PGADMIN_DEFAULT_EMAIL=daphne
      - PGADMIN_DEFAULT_PASSWORD=daphne
